image: golang:alpine

before_script:
  - "go get -u github.com/ogier/pflag"
  - "mkdir -p /go/src/maunium.net/go"
  - "ln -s /builds/Tulir293/maulias /go/src/maunium.net/go/maulias"

build:
  script:
    - "env GOOS=linux GOARCH=amd64 go build -o maulias_amd64"
    - "env GOOS=linux GOARCH=arm go build -o maulias_arm"
    - "env GOOS=windows GOARCH=amd64 go build -o maulias_amd64.exe"
  stage: build
  tags:
    - golang
  artifacts:
    paths:
    - maulias_amd64
    - maulias_arm
    - maulias_amd64.exe
    - LICENSE
